app = require('app')
# Module to control application life.
fs = require('fs')
BrowserWindow = require('browser-window')
windowManager = require('electron-window-manager')
#const {app, BrowserWindow} = require('electron')
#var testcc = require('cson-config').load();
config = global['config'] = require('config.cson')
app.on 'window-all-closed', ->
# if (process.platform != 'darwin')
  app.quit()
  return
app.on 'before-quit', ->
  app.quit()
  return
app.on 'ready', ->
  windowManager.init
    'devMode': false
    'appBase': __dirname
    'onLoadFailure': (window) ->
    'layouts':
      'default': '/layouts/default.html'
      'p5': '/windows/p5test1.html'

  windowManager.setDefaultSetup config.defaultWindowSetup
  windowManager.templates.set 'nonode', config.noNodeWindowSetup

  we = windowManager.createNew('Editor', 'Editor', 'file://' + __dirname + '/editor/index.html')
  we.open()
  we.move 'right'
  we.execute 'justUpdate()'
  #
  #windowManager.createNew('bozon', 'Bozon', 'file://' + __dirname + '/bozon/index.html').open();
  #
  we1 = windowManager.createNew('Editor2', 'Editor', 'file://' + __dirname + '/editor/index.html');
  we1.open();
  we1.move('right');
  we1.execute('justUpdate()');

  we2 = windowManager.createNew('Editor3', 'Editor', 'file://' + __dirname + '/editor/index.html');
  we2.open();
  we2.move('right');
  we2.execute('justUpdate()');
  #//wb = windowManager.get('bozon')
  #s = String(fs.readFileSync('bozon/bozon.js'))
  #cpath = 'file://' + app.getAppPath() + '/bozon/index.html';
  #
  #as = s.split('\n\n').forEach(load)
  #function load(v, i) {
  #  var w = windowManager.createNew('bozon_' + i, 'Bozon', cpath);
  #  w.open()
  #  w.set('frame', false);
  #  w.execute('bozid = ' + i + ';')
  #  w.onReady(true, function (w) {
  #
  #    w.content().send('justSource', v)
  #    w.execute('syncSizeLines()')
  #    w.content().send('justScrollAll')
  #  });
  #
  #
  #}
  return

# ---
# generated by js2coffee 2.1.0